const fs = require('fs');
const inquirer = require('inquirer');
// const util = require('util');

inquirer.createPromptModule(
    [
        {
            type:
            message:
            name: 
        },
        {
            type:
            message:
            name: 
        },
        {
            type:
            message:
            name:            
        },
        {
            type:
            message:
            name: 
        },
        {
            type:
            message:
            name: 
        },
        {
            type:
            message:
            name: 
        },
        {
            type:
            message:
            name: 
        },
        {
            type:
            message:
            name: 
        },
        {
            type:
            message:
            name:            
        },
        {
            type:
            message:
            name: 
        },
        {
            type:
            message:
            name: 
        },
        {
            type:
            message:
            name: 
        },
    ]
);